import { useState } from 'react'

function ScheduleManager({ schedules, onSave, onClose, embedded }) {
  const [activeTab, setActiveTab] = useState('nannies')
  const [editingSchedule, setEditingSchedule] = useState(null)
  
  const [formData, setFormData] = useState({
    type: 'nanny',
    title: '',
    person: '',
    days: [],
    startTime: '09:00',
    endTime: '17:00',
    hourlyRate: '',
    venmoUsername: '',
    notes: ''
  })
  
  const generatePDF = (nanny) => {
    const content = `
NANNY SCHEDULE
${nanny.title}${nanny.person ? ' - ' + nanny.person : ''}

SCHEDULE:
${nanny.days.join(', ')}
${nanny.startTime} - ${nanny.endTime}

HOURS: ${calculateWeeklyHours(nanny)} hours/week

${nanny.hourlyRate ? `RATE: $${nanny.hourlyRate}/hour
WEEKLY COST: $${calculateWeeklyCost(nanny).toFixed(2)}` : ''}

${nanny.venmoUsername ? `PAYMENT: Venmo @${nanny.venmoUsername}` : ''}

${nanny.notes ? `NOTES:\n${nanny.notes}` : ''}

Generated by MomOps
${new Date().toLocaleDateString()}
    `.trim()
    
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${nanny.title.replace(/\s+/g, '-')}-schedule.txt`
    a.click()
    URL.revokeObjectURL(url)
    
    alert('Schedule downloaded! You can convert this to PDF using any text-to-PDF converter.')
  }
  
  const handleVenmoPay = (nanny) => {
    if (!nanny.venmoUsername) {
      alert('Please add Venmo username to this nanny\'s profile first.')
      return
    }
    
    const amount = calculateWeeklyCost(nanny).toFixed(2)
    const note = `${nanny.title} - Week of ${new Date().toLocaleDateString()}`
    const venmoUrl = `https://venmo.com/${nanny.venmoUsername}?txn=pay&amount=${amount}&note=${encodeURIComponent(note)}`
    
    window.open(venmoUrl, '_blank')
  }
  
  const daysOfWeek = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
  
  const handleDayToggle = (day) => {
    setFormData(prev => ({
      ...prev,
      days: prev.days.includes(day) 
        ? prev.days.filter(d => d !== day)
        : [...prev.days, day]
    }))
  }
  
  const handleSubmit = () => {
    if (!formData.title || formData.days.length === 0) {
      alert('Please fill in required fields')
      return
    }
    
    const schedule = {
      id: editingSchedule?.id || Date.now(),
      ...formData
    }
    
    onSave(schedule)
    resetForm()
  }
  
  const resetForm = () => {
    setFormData({
      type: 'nanny',
      title: '',
      person: '',
      days: [],
      startTime: '09:00',
      endTime: '17:00',
      hourlyRate: '',
      venmoUsername: '',
      notes: ''
    })
    setEditingSchedule(null)
  }
  
  const handleEdit = (schedule) => {
    setFormData(schedule)
    setEditingSchedule(schedule)
  }
  
  const handleDelete = (id) => {
    if (confirm('Delete this schedule?')) {
      onSave(null, id)
    }
  }
  
  const calculateWeeklyHours = (schedule) => {
    const start = schedule.startTime.split(':')
    const end = schedule.endTime.split(':')
    const hours = (parseInt(end[0]) - parseInt(start[0])) + (parseInt(end[1]) - parseInt(start[1])) / 60
    return hours * schedule.days.length
  }
  
  const calculateWeeklyCost = (schedule) => {
    if (!schedule.hourlyRate) return 0
    return calculateWeeklyHours(schedule) * parseFloat(schedule.hourlyRate)
  }
  
  const nannies = schedules.filter(s => s.type === 'nanny')
  const workSchedules = schedules.filter(s => s.type === 'work')
  const activities = schedules.filter(s => s.type === 'activity')
  
  const content = (
    <>
      {!embedded && (
        <div className="modal-header">
          <h2>Schedule Manager</h2>
          <button className="close-btn" onClick={onClose}>×</button>
        </div>
      )}
      {embedded && (
        <div className="modal-header">
          <div className="header-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <circle cx="12" cy="12" r="9" stroke="#FCD34D" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M12 6V12L16 14" stroke="#FCD34D" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </div>
          <h2>Schedules</h2>
        </div>
      )}
        
        <div className="schedule-tabs">
          <button 
            className={`tab-btn ${activeTab === 'nannies' ? 'active' : ''}`}
            onClick={() => setActiveTab('nannies')}
          >
            Nannies
          </button>
          <button 
            className={`tab-btn ${activeTab === 'work' ? 'active' : ''}`}
            onClick={() => setActiveTab('work')}
          >
            Work Schedule
          </button>
        </div>
        
        <div className="modal-body">
          {activeTab === 'nannies' && (
            <div className="schedule-list">
              <h4>Nanny Schedules</h4>
              {nannies.map(nanny => (
                <div key={nanny.id} className="schedule-item">
                  <div className="schedule-item-header">
                    <div>
                      <strong>{nanny.title}</strong>
                      {nanny.person && <span className="person-name"> • {nanny.person}</span>}
                    </div>
                    <div className="schedule-actions">
                      <button className="action-icon-btn" onClick={() => generatePDF(nanny)} title="Generate PDF">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path d="M14 2H6C5.46957 2 4.96086 2.21071 4.58579 2.58579C4.21071 2.96086 4 3.46957 4 4V20C4 20.5304 4.21071 21.0391 4.58579 21.4142C4.96086 21.7893 5.46957 22 6 22H18C18.5304 22 19.0391 21.7893 19.4142 21.4142C19.7893 21.0391 20 20.5304 20 20V8L14 2Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                          <path d="M14 2V8H20" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                        </svg>
                      </button>
                      {nanny.hourlyRate && (
                        <button className="action-icon-btn venmo" onClick={() => handleVenmoPay(nanny)} title="Pay via Venmo">
                          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2Z" stroke="currentColor" strokeWidth="2"/>
                            <path d="M8 9L12 15L16 9" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                          </svg>
                        </button>
                      )}
                      <button className="edit-btn" onClick={() => handleEdit(nanny)}>Edit</button>
                      <button className="delete-btn" onClick={() => handleDelete(nanny.id)}>Delete</button>
                    </div>
                  </div>
                  <div className="schedule-details">
                    <div>{nanny.days.join(', ')}</div>
                    <div>{nanny.startTime} - {nanny.endTime}</div>
                    {nanny.hourlyRate && (
                      <div className="cost-info">
                        ${nanny.hourlyRate}/hr • {calculateWeeklyHours(nanny)}h/week • ${calculateWeeklyCost(nanny).toFixed(2)}/week
                      </div>
                    )}
                    {nanny.venmoUsername && (
                      <div className="venmo-info-row">
                        <span className="venmo-info">Venmo: @{nanny.venmoUsername}</span>
                        <button className="venmo-pay-btn" onClick={() => handleVenmoPay(nanny)}>
                          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2Z" fill="currentColor"/>
                            <path d="M8 9L12 15L16 9" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                          </svg>
                          Pay Now
                        </button>
                      </div>
                    )}
                  </div>
                </div>
              ))}
              
              <div className="add-schedule-form">
                <h5>{editingSchedule ? 'Edit' : 'Add'} Nanny Schedule</h5>
                
                <div className="form-group">
                  <label>Name/Title</label>
                  <input 
                    type="text"
                    value={formData.title}
                    onChange={(e) => setFormData({...formData, title: e.target.value})}
                    placeholder="e.g., Morning Nanny"
                    className="input"
                  />
                </div>
                
                <div className="form-group">
                  <label>Nanny Name (optional)</label>
                  <input 
                    type="text"
                    value={formData.person}
                    onChange={(e) => setFormData({...formData, person: e.target.value})}
                    placeholder="e.g., Sarah"
                    className="input"
                  />
                </div>
                
                <div className="form-group">
                  <label>Days</label>
                  <div className="days-grid">
                    {daysOfWeek.map(day => (
                      <button
                        key={day}
                        className={`day-btn ${formData.days.includes(day) ? 'active' : ''}`}
                        onClick={() => handleDayToggle(day)}
                      >
                        {day.slice(0, 3)}
                      </button>
                    ))}
                  </div>
                </div>
                
                <div className="form-row">
                  <div className="form-group">
                    <label>Start Time</label>
                    <input 
                      type="time"
                      value={formData.startTime}
                      onChange={(e) => setFormData({...formData, startTime: e.target.value})}
                      className="input"
                    />
                  </div>
                  
                  <div className="form-group">
                    <label>End Time</label>
                    <input 
                      type="time"
                      value={formData.endTime}
                      onChange={(e) => setFormData({...formData, endTime: e.target.value})}
                      className="input"
                    />
                  </div>
                </div>
                
                <div className="form-group">
                  <label>Hourly Rate (optional)</label>
                  <input 
                    type="number"
                    value={formData.hourlyRate}
                    onChange={(e) => setFormData({...formData, hourlyRate: e.target.value})}
                    placeholder="e.g., 20"
                    className="input"
                  />
                </div>
                
                <div className="form-group">
                  <label>Venmo Username (optional)</label>
                  <div className="input-with-prefix">
                    <span className="input-prefix">@</span>
                    <input 
                      type="text"
                      value={formData.venmoUsername}
                      onChange={(e) => setFormData({...formData, venmoUsername: e.target.value})}
                      placeholder="username"
                      className="input"
                    />
                  </div>
                </div>
                
                <div className="form-group">
                  <label>Notes (optional)</label>
                  <textarea 
                    value={formData.notes}
                    onChange={(e) => setFormData({...formData, notes: e.target.value})}
                    placeholder="Special instructions..."
                    className="textarea"
                    rows="2"
                  />
                </div>
                
                <div className="form-actions">
                  {editingSchedule && (
                    <button className="btn btn-secondary" onClick={resetForm}>Cancel</button>
                  )}
                  <button className="btn btn-primary" onClick={handleSubmit}>
                    {editingSchedule ? 'Update' : 'Add'} Schedule
                  </button>
                </div>
              </div>
            </div>
          )}
          
          {activeTab === 'work' && (
            <div>
              <div className="calendar-connect">
                <h5>Connect Your Calendar</h5>
                <p style={{ fontSize: '0.875rem', color: 'var(--text-tertiary)', marginBottom: '1rem' }}>
                  Sync your work schedule with Google Calendar or Outlook
                </p>
                <div className="calendar-buttons">
                  <button className="calendar-btn" onClick={() => alert('Google Calendar integration coming soon!')}>
                    <span>◆</span>
                    <span>Google Calendar</span>
                  </button>
                  <button className="calendar-btn" onClick={() => alert('Outlook integration coming soon!')}>
                    <span>◆</span>
                    <span>Outlook</span>
                  </button>
                </div>
              </div>
              
              <div className="info-box">
                <p><strong>Coming Soon:</strong></p>
                <p>• Automatic sync with your work calendar</p>
                <p>• Conflict detection with nanny schedules</p>
                <p>• Meeting reminders coordinated with baby care</p>
              </div>
            </div>
          )}
        </div>
    </>
  )
  
  if (embedded) {
    return <div className="embedded-view">{content}</div>
  }
  
  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="schedule-modal" onClick={(e) => e.stopPropagation()}>
        {content}
      </div>
    </div>
  )
}

export default ScheduleManager
